"""init schema

Revision ID: 770591043f1d
Revises: 
Create Date: 2026-08-25 23:16:52.179577
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '770591043f1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.String(length=48), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('zone', sa.String(length=80), nullable=False),
    sa.Column('orientation', sa.String(length=40), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('last_environment', sa.String(length=40), nullable=False),
    sa.Column('ai_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_camera_id'), ['camera_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cameras_zone'), ['zone'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.String(length=48), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vehicle_class', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('center', sa.JSON(), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index('ix_detections_cam_ts', ['camera_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_detection_id'), ['detection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_tracking_id'), ['tracking_id'], unique=False)

    op.create_table('plate_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=True),
    sa.Column('raw_text', sa.String(length=40), nullable=False),
    sa.Column('normalized_text', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ocr_engine', sa.String(length=20), nullable=False),
    sa.Column('valid_format', sa.Boolean(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('plate_bbox', sa.JSON(), nullable=False),
    sa.Column('crop_path', sa.String(length=300), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plate_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plate_reads_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_normalized_text'), ['normalized_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_tracking_id'), ['tracking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_vehicle_uid'), ['vehicle_uid'], unique=False)

    op.create_table('speed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('elapsed_s', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('excess_kmh', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=True),
    sa.Column('is_violation', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speed_events', schema=None) as batch_op:
        batch_op.create_index('ix_speed_cam_ts', ['camera_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_is_violation'), ['is_violation'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_speed_kmh'), ['speed_kmh'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_tracking_id'), ['tracking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_events_vehicle_uid'), ['vehicle_uid'], unique=False)

    op.create_table('track_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('center', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_points_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_points_tracking_id'), ['tracking_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('vehicle_class', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_frame', sa.Integer(), nullable=False),
    sa.Column('last_frame', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_tracking_id'), ['tracking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_vehicle_uid'), ['vehicle_uid'], unique=False)

    op.create_table('traffic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_type_ts', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_tracking_id'), ['tracking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_events_vehicle_uid'), ['vehicle_uid'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicle_journeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('first_camera', sa.String(length=40), nullable=False),
    sa.Column('last_camera', sa.String(length=40), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('hop_count', sa.Integer(), nullable=False),
    sa.Column('path', sa.JSON(), nullable=False),
    sa.Column('association_confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_journeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_journeys_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_journeys_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_journeys_vehicle_uid'), ['vehicle_uid'], unique=False)

    op.create_table('vehicle_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_class', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('plate_confidence', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('frame_path', sa.String(length=300), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_vehicle_ts', ['vehicle_uid', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_observations_vehicle_uid'), ['vehicle_uid'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_uid', sa.String(length=40), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_class', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('plate_confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate_number'), ['plate_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_uid'), ['vehicle_uid'], unique=True)

    op.create_table('camera_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_pk', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('line_a', sa.JSON(), nullable=False),
    sa.Column('line_b', sa.JSON(), nullable=False),
    sa.Column('real_distance_m', sa.Float(), nullable=False),
    sa.Column('image_points', sa.JSON(), nullable=False),
    sa.Column('world_points', sa.JSON(), nullable=False),
    sa.Column('measurement_area', sa.JSON(), nullable=False),
    sa.Column('direction', sa.String(length=40), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('frame_width', sa.Integer(), nullable=False),
    sa.Column('frame_height', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_pk'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_calibrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_calibrations_camera_pk'), ['camera_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_calibrations_camera_pk'))

    op.drop_table('camera_calibrations')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_number'))
        batch_op.drop_index(batch_op.f('ix_vehicles_last_seen'))
        batch_op.drop_index(batch_op.f('ix_vehicles_first_seen'))

    op.drop_table('vehicles')
    with op.batch_alter_table('vehicle_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_plate_number'))
        batch_op.drop_index(batch_op.f('ix_vehicle_observations_camera_id'))
        batch_op.drop_index('ix_obs_vehicle_ts')

    op.drop_table('vehicle_observations')
    with op.batch_alter_table('vehicle_journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_journeys_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_vehicle_journeys_plate_number'))
        batch_op.drop_index(batch_op.f('ix_vehicle_journeys_first_seen'))

    op.drop_table('vehicle_journeys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('traffic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_events_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_plate_number'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_traffic_events_camera_id'))
        batch_op.drop_index('ix_events_type_ts')

    op.drop_table('traffic_events')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_tracks_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_first_seen'))
        batch_op.drop_index(batch_op.f('ix_tracks_camera_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('track_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_points_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_track_points_camera_id'))

    op.drop_table('track_points')
    with op.batch_alter_table('speed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speed_events_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_speed_events_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_speed_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_speed_events_speed_kmh'))
        batch_op.drop_index(batch_op.f('ix_speed_events_plate_number'))
        batch_op.drop_index(batch_op.f('ix_speed_events_is_violation'))
        batch_op.drop_index(batch_op.f('ix_speed_events_camera_id'))
        batch_op.drop_index('ix_speed_cam_ts')

    op.drop_table('speed_events')
    with op.batch_alter_table('plate_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plate_reads_vehicle_uid'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_timestamp'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_normalized_text'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_camera_id'))

    op.drop_table('plate_reads')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_detections_timestamp'))
        batch_op.drop_index(batch_op.f('ix_detections_detection_id'))
        batch_op.drop_index(batch_op.f('ix_detections_camera_id'))
        batch_op.drop_index('ix_detections_cam_ts')

    op.drop_table('detections')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_zone'))
        batch_op.drop_index(batch_op.f('ix_cameras_camera_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alerts_camera_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
